draw_set_color(c_white)
draw_set_alpha(.9)
draw_rectangle(x-width/2,
			   y-height/2,
			   x+width/2,
			   y+height/2,
			   false)
draw_set_alpha(1)
draw_set_color(c_black)
draw_set_halign(fa_center)
draw_set_valign(fa_middle)
draw_text(x,y,text)
draw_set_color(c_white)